# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src
COPY /Reunite /src/Reunite
RUN dotnet restore "Reunite/Reunite.csproj"
RUN dotnet build "Reunite/Reunite.csproj" -c Release -o /app/build

# Publish stage
FROM build AS publish
RUN dotnet publish "Reunite/Reunite.csproj" -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/sdk:8.0

# Install dotnet-ef CLI tool
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet tool install --global dotnet-ef

WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://*:5000
EXPOSE 5000
ENTRYPOINT ["dotnet", "Reunite.dll"]